name: horoscope_app
description: A modern horoscope app with beautiful UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.jpg
    - assets/icons/cancer.png
    - assets/icons/leo.png
    - assets/icons/earth.png
    - assets/icons/feminine.png
    - assets/icons/spinner.gif
